### ISSUE TITLE
Basic test fails with division by zero

### ISSUE THREAD

**Issue by wenzeslaus** [ncsu-landscape-dynamics/pathways-simulation#21]
The basic test [is failing](https://github.com/ncsu-landscape-dynamics/pathways-simulation/pull/20/checks?check_run_id=606491028) with:

```
Run python -m pathways --num-simulations 5 --num-shipments 50 --config-file config.yml
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/runner/work/pathways-simulation/pathways-simulation/pathways/__main__.py", line 25, in <module>
    main()
  File "/home/runner/work/pathways-simulation/pathways-simulation/pathways/app.py", line 135, in main
    pretty=args.pretty,
  File "/home/runner/work/pathways-simulation/pathways-simulation/pathways/simulation.py", line 281, in run_simulation
    pretty=pretty,
  File "/home/runner/work/pathways-simulation/pathways-simulation/pathways/simulation.py", line 219, in simulation
    / success_rates.true_positive,
ZeroDivisionError: float division by zero
```

**Comment by wenzeslaus** [comment]
Through using *Blame* on the current version of outputs.py and then using it again on the simulation.py file version before splitting the files, I found that the current code in outputs.py comes from the original "what positive means" change: 8a21d83e21902f34. The diff explains how the error was introduced. It manifested only now because the true_positives attribute was unused up until 9d565f056868e033.
