### ISSUE TITLE
CLI test fails because false_negative == 0 

### ISSUE THREAD

**Issue by wenzeslaus** [ncsu-landscape-dynamics/pathways-simulation#26]
The test of CLI (tests/test_cli.py) fails with `ZeroDivisionError: division by zero` because of line    `missed_infestation_rate / success_rates.false_negative`. Having zero FN is expected, so it would be best to account for this in computation of the rate, e.g. by assigning `None` in this case (the potential post-processing will have to account for that).

If this is a priority or not mainly depends on whether or not this happens with the cases we want to explore first.

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/runner/work/pathways-simulation/pathways-simulation/pathways/__main__.py", line 25, in <module>
    main()
  File "/home/runner/work/pathways-simulation/pathways-simulation/pathways/app.py", line 135, in main
    pretty=args.pretty,
  File "/home/runner/work/pathways-simulation/pathways-simulation/pathways/simulation.py", line 230, in run_simulation
    pretty=pretty,
  File "/home/runner/work/pathways-simulation/pathways-simulation/pathways/simulation.py", line 185, in simulation
    missed_infestation_rate / success_rates.false_negative
ZeroDivisionError: division by zero
```

**Comment by wenzeslaus** [comment]
Fixed by #28 (b65183c)
